apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivist-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archivist-database
  template:
    metadata:
      labels:
        app: archivist-database
    spec:
      containers:
        - name: archivist-database
          image: postgres:12.2
          env:
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_DB
              value: "archivist"
---
apiVersion: v1
kind: Service
metadata:
  name: archivist-database-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: archivist-database
  ports:
    - name: archivist-database
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: archivist-database-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: archivist-database
  ports:
    - name: archivist-database
      protocol: TCP
      port: 5301
      targetPort: 5432

