apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - ./*.depl.yaml
      - ./*.srv.yaml
build:
  local:
    concurrency: 3
    push: false
  artifacts:
    - image: dormammun/gravity-passport
      context: "../../"
      sync:
        manual:
          - src: "applications/**/src/**/*"
            dest: "."
          - src: "packages/**/src/**/*"
            dest: "."
      docker:
        dockerfile: "deployment/images/passport/Dockerfile"
    - image: dormammun/gravity-archivist
      context: "../../"
      sync:
        manual:
          - src: "applications/**/src/**/*"
            dest: "."
          - src: "packages/**/src/**/*"
            dest: "."
      docker:
        dockerfile: "deployment/images/archivist/Dockerfile"
    - image: dormammun/gravity-telegraph
      context: "../../"
      sync:
        manual:
          - src: "applications/**/src/**/*"
            dest: "."
          - src: "packages/**/src/**/*"
            dest: "."
      docker:
        dockerfile: "deployment/images/telegraph/Dockerfile"
    - image: dormammun/gravity-web
      context: "../../"
      sync:
        manual:
          - src: "applications/**/src/**/*"
            dest: "."
          - src: "packages/**/src/**/*"
            dest: "."
      docker:
        dockerfile: "deployment/images/web/Dockerfile"