apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: dormammun/gravity-web
          env:
            - name: NEXT_PUBLIC_PASSPORT_API_URL
              value: "https://passport.gravity.io"
            - name: NEXT_PUBLIC_TELEGRAPH_API_URL
              value: "https://telegraph.gravity.io"
            - name: NEXT_PUBLIC_ARCHIVIST_API_URL
              value: "https://archivist.gravity.io"
---
apiVersion: v1
kind: Service
metadata:
  name: web-cluster-ip-srv
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000

