apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archivist
  template:
    metadata:
      labels:
        app: archivist
    spec:
      initContainers:
        - name: test-postgres
          image: postgres:12.2
          env:
            - name: DB_HOST
              value: "archivist-database-cluster-ip"
            - name: DB_USER
              value: "root"
          command: [ 'sh', '-c' ]
          args:
            - |
              until pg_isready -h $DB_HOST -U $DB_USER
              do
                echo "Waiting for postgres..."
                sleep 2
              done
        - name: test-nats
          image: curlimages/curl:7.87.0
          env:
            - name: NATS_HOST
              value: "http://nats-cluster-ip:8222/varz"
          command: [ 'sh', '-c' ]
          args:
            - |
              until curl -s $NATS_HOST > /dev/null
              do
                echo "Waiting for nats..."
                sleep 2
              done
      containers:
        - name: archivist
          image: dormammun/gravity-archivist
          env:
            - name: DEBUG
              value: "true"
            - name: PORT
              value: "3000"
            - name: JWT_SECRET_KEY
              value: "secret-key"
            - name: DB_HOST
              value: "postgresql://root:root@archivist-database-cluster-ip/archivist"
            - name: NATS_URL
              value: 'http://nats-cluster-ip:4222'
            - name: NATS_CLUSTER_ID
              value: '@gravity/icebreaker'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: archivist-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: archivist
  ports:
    - name: archivist
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: archivist-debug-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: archivist
  ports:
    - name: archivist-debug
      protocol: TCP
      port: 9201
      targetPort: 9229
