apiVersion: apps/v1
kind: Deployment
metadata:
  name: passport-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passport
  template:
    metadata:
      labels:
        app: passport
    spec:
      initContainers:
        - name: test-postgres
          image: postgres:12.2
          env:
            - name: DB_HOST
              value: "passport-db-cluster-ip-srv"
            - name: DB_USER
              value: "root"
          command: ['sh', '-c']
          args:
            - |
              until pg_isready -h $DB_HOST -U $DB_USER
              do
                echo "Waiting for postgres..."
                sleep 2
              done
        - name: test-nats
          image: curlimages/curl:7.87.0
          env:
            - name: NATS_HOST
              value: "http://nats-cluster-ip-srv:8222/varz"
          command: ['sh', '-c']
          args:
            - |
              until curl -s $NATS_HOST > /dev/null
              do
                echo "Waiting for nats..."
                sleep 2
              done
      containers:
        - name: passport
          image: dormammun/gravity-passport
          env:
            - name: PORT
              value: "3000"
            - name: JWT_SECRET_KEY
              value: "secret-key"
            - name: DB_HOST
              value: "postgresql://root:root@passport-db-cluster-ip-srv/passport"
            - name: NATS_URL
              value: 'http://nats-cluster-ip-srv:4222'
            - name: NATS_CLUSTER_ID
              value: '@gravity/icebreaker'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: passport-cluster-ip-srv
spec:
  type: ClusterIP
  selector:
    app: passport
  ports:
    - name: passport
      protocol: TCP
      port: 3000
      targetPort: 3000

