apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: dormammun/gravity-web
          env:
            - name: DEBUG
              value: "true"
            - name: NEXT_PUBLIC_API_URL
              value: "http://gravity.io"
---
apiVersion: v1
kind: Service
metadata:
  name: web-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-debug-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - name: web-debug
      protocol: TCP
      port: 9204
      targetPort: 9229