import {type ReactNode} from 'react'

import {QueryProviders} from '@app/library/providers/query'

import '@app/styles/tailwind.build.css'

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default async function RootLayout({children}: {children: ReactNode}) {
  return (
    <html lang="en">
      <body>
        <main className="h-screen">
          <QueryProviders>{children}</QueryProviders>
        </main>
      </body>
    </html>
  )
}
