import {type ReactNode} from 'react'

import {passportClient} from '@app/library/api-client'
import {QueryProvider} from '@app/library/storage'

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default async function RootLayout({children}: {children: ReactNode}) {
  const {user} = await passportClient.currentUser.query()
  return (
    <html lang="en">
      <body>
        <main>
          <QueryProvider currentUser={user}>{children}</QueryProvider>
        </main>
      </body>
    </html>
  )
}
