import {type ReactNode} from 'react'

import {passportClient} from '@app/library/passport-client'
import {StorageProvider} from '@app/library/storage'

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default async function RootLayout({children}: {children: ReactNode}) {
  const {user} = await passportClient.currentUser.query()
  return (
    <html lang="en">
      <body>
        <StorageProvider currentUser={user}>{children}</StorageProvider>
      </body>
    </html>
  )
}
