name: Running @applications/archivist tests

env:
  JWT_SECRET_KEY: secret-key

on:
  pull_request:
    paths:
      - 'applications/archivist/**'
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm run setup --filter=@applications/archivist
      - run: npm install --workspaces=false
      - run: npm run lint --filter=@applications/archivist
  typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install --workspace=@applications/archivist --include-workspace-root --verbose
      - run: npm run typecheck --workspace=@applications/archivist
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install --workspace=@applications/archivist --include-workspace-root --verbose
      - run: npm run build --workspace=@applications/archivist