name: Running @packages tests

env:
  NEXT_PUBLIC_API_URL: fake-api-url
  JWT_SECRET_KEY: secret-key

on:
  pull_request:
    paths:
      - 'packages/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci
      - run: npm typecheck
      - run: npm lint
      - run: npm build