name: Running packages tests

env:
  JWT_SECRET_KEY: secret-key

on:
  pull_request:
    paths:
      - 'packages/**'
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci --include-workspace-root
      - run: npm run lint
  typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci --workspaces --include-workspace-root
      - run: npm run typecheck
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci --workspaces --include-workspace-roots
      - run: npm run build
