name: Running @packages tests

on:
  pull_request:
    paths:
      - 'applications/packages/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.22.0
      - run: pnpm install
      - run: pnpm typecheck
      - run: pnpm lint
      - run: pnpm build