name: Running @applications/passport tests

env:
  JWT_SECRET_KEY: secret-key

on:
  pull_request:
    paths:
      - 'applications/passport/**'
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install --workspace=@applications/passport --include-workspace-root --verbose
      - run: npm run lint --workspace=@applications/passport
      - run: npm run typecheck --workspace=@applications/passport
  typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install --workspace=@applications/passport --include-workspace-root --verbose
      - run: npm run typecheck --workspace=@applications/passport
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install --workspace=@applications/passport --include-workspace-root --verbose
      - run: npm run build --workspace=@applications/passport