name: Running @applications/passport tests

env:
  JWT_SECRET_KEY: secret-key

on:
  pull_request:
    paths:
      - 'applications/passport/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci --workspace=@applications/passport --include-workspace-root
      - run: npm run prisma:generate --workspace=@applications/passport
      - run: npm run typecheck --workspace=@applications/passport
      - run: npm run lint --workspace=@applications/passport
      - run: npm run build --workspace=@applications/passport