name: Running @applications/passport tests

env:
  JWT_SECRET_KEY: secret-key

on:
  pull_request:
    paths:
      - 'applications/passport/**'
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci -w @applications/passport --include-workspace-root
      - run: npm run build:passport
      - run: npm run lint:passport
  typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci -w @applications/passport --include-workspace-root
      - run: npm run build:passport
      - run: npm run typecheck:passport