name: Running @applications/telegraph tests

env:
  JWT_SECRET_KEY: secret-key

on:
  pull_request:
    paths:
      - 'applications/telegraph/**'
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci -w @applications/telegraph --include-workspace-root
      - run: npm run build:telegraph
      - run: npm run lint:telegraph
  typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci -w @applications/telegraph --include-workspace-root
      - run: npm run build:telegraph
      - run: npm run typecheck:telegraph