name: Running @applications/telegraph tests

env:
  JWT_SECRET_KEY: secret-key

on:
  pull_request:
    paths:
      - 'applications/telegraph/**'
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install --workspace=@applications/telegraph --include-workspace-root
      - run: npm run lint -- --filter=@applications/telegraph
      - run: npm run typecheck --filter=@applications/telegraph
  typecheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install --workspace=@applications/telegraph --include-workspace-root
      - run: npm run typecheck --filter=@applications/telegraph
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install --workspace=@applications/telegraph --include-workspace-root
      - run: npm run build --workspace=@applications/telegraph