name: Running @applications/telegraph tests

on:
  pull_request:
    paths:
      - 'applications/telegraph/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.22.0
      - run: pnpm --filter @applications/telegraph... install
      - run: pnpm --filter @applications/telegraph... typecheck
      - run: pnpm --filter @applications/telegraph... lint
      - run: pnpm --filter @applications/telegraph... build