name: Running @applications/telegraph tests

env:
  JWT_SECRET_KEY: secret-key

on:
  pull_request:
    paths:
      - 'applications/telegraph/**'
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci --workspace=@applications/telegraph --include-workspace-root
      - run: npm run telegraph:lint
  typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci ---workspace=@applications/telegraph --include-workspace-root
      - run: npm run telegraph:typecheck
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci ---workspace=@applications/telegraph --include-workspace-root
      - run: npm run telegraph:build