name: Running @applications/web tests

env:
  NEXT_PUBLIC_API_URL: fake-api-url

on:
  pull_request:
    paths:
      - 'applications/web/**'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci --workspace=@applications/web --include-workspace-root --verbose
      - run: npm run typecheck --workspace=@applications/web
      - run: npm run lint --workspace=@applications/web
      - run: npm run build --workspace=@applications/web