name: Running @applications/web tests

env:
  NEXT_PUBLIC_API_URL: fake-api-url

on:
  pull_request:
    paths:
      - 'applications/web/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.22.0
      - run: pnpm --filter @applications/web... install
      - run: pnpm --filter @applications/web... typecheck
      - run: pnpm --filter @applications/web... lint
      - run: pnpm --filter @applications/web... build