name: Running @applications/web tests

env:
  NEXT_PUBLIC_API_URL: fake-api-url
  JWT_SECRET_KEY: secret-key

on:
  pull_request:
    paths:
      - 'applications/web/**'
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install --workspace=@applications/web --install-workspace-root
      - run: npm run lint -- --filter=@applications/web
      - run: npm run typecheck --filter=@applications/web
  typecheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install --workspace=@applications/web --install-workspace-root
      - run: npm run typecheck --filter=@applications/web
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install --workspace=@applications/web --install-workspace-root
      - run: npm run build --workspace=@applications/web