name: Running @applications/web tests

env:
  NEXT_PUBLIC_API_URL: fake-api-url
  NEXT_PUBLIC_INTERNAL_API_URL: fake-internal-api-url
  JWT_SECRET_KEY: secret-key

on:
  pull_request:
    paths:
      - 'applications/web/**'
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci --workspace=@applications/web --include-workspace-root
      - run: npm run web:lint
  typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci ---workspace=@applications/web --include-workspace-root
      - run: npm run web:typecheck
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci ---workspace=@applications/web --include-workspace-root
      - run: npm run web:build